# Generated by Django 4.1 on 2025-03-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                ("deptno", models.IntegerField(primary_key=True, serialize=False)),
                ("dname", models.CharField(max_length=14)),
                ("loc", models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name="Emp",
            fields=[
                ("empno", models.IntegerField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=10)),
                ("job", models.CharField(max_length=9)),
                ("mgr", models.IntegerField()),
                ("hiredate", models.DateField()),
                ("sal", models.FloatField()),
                ("comm", models.FloatField()),
                (
                    "deptno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dept"
                    ),
                ),
            ],
        ),
    ]
