# Generated by Django 4.1 on 2025-03-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_dept_dname_alter_emp_comm_alter_emp_hiredate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salgrade",
            fields=[
                ("grade", models.IntegerField(primary_key=True, serialize=False)),
                ("losal", models.IntegerField()),
                ("hisal", models.IntegerField()),
            ],
        ),
    ]
