# Generated by Django 5.1.6 on 2025-05-03 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scname", models.CharField(max_length=100)),
                ("scaddress", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stname", models.CharField(max_length=100)),
                ("stage", models.IntegerField()),
                (
                    "scname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.school"
                    ),
                ),
            ],
        ),
    ]
