# Generated by Django 4.1 on 2025-03-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpage",
            name="email",
            field=models.EmailField(default="hai@gmail.com", max_length=264),
        ),
    ]
