# Generated by Django 5.1.6 on 2025-03-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_topic_webpage_topic_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="name",
            field=models.CharField(max_length=264),
        ),
    ]
